### ISSUE TITLE
liner: function not supported in this terminal

### ISSUE THREAD

**Issue by gaowanliang** [tickstep/cloudpan189-go#19]
在docker环境下的jupyter notebook中使用login函数是会出现这个情况,是不支持这种不回显的输入框导致的，建议login函数直接加一个这样的登录方式
```
cloudpan189-go login <手机号/邮箱/别名> <密码>
```

**Comment by tickstep** [comment]
是什么docker镜像呀？有知道它是基于哪种linux发行版吗？

**Comment by gaowanliang** [comment]
可以直接使用Google的colab进行测试，一套完整的使用规则如下
```
!wget https://github.com/tickstep/cloudpan189-go/releases/download/v0.0.9/cloudpan189-go-v0.0.9-linux-amd64.zip
!unzip cloudpan189-go-v0.0.9-linux-amd64.zip
!mv cloudpan189-go-v0.0.9-linux-amd64/cloudpan189-go  cloudpan189-go
!chmod +x cloudpan189-go
!./cloudpan189-go login
```

**Comment by tickstep** [comment]
直接命令模式试试

cloudpan189-go login -username=tickstep -password=123xxx

**Comment by gaowanliang** [comment]
> 直接命令模式试试
> 
> cloudpan189-go login -username=tickstep -password=123xxx

直接登录肯定是没有问题的，是因为输入密码时使用的输入方式无法对应一种输入框才导致的这个问题，但是这种登录方式并没有在document里给出

**Comment by tickstep** [comment]
命令帮助有

cloudpan189-go help login

**Comment by y377** [comment]
是啊，之前在Windows下运行的很完美，现在centos7请问怎么运行啊？也使用yum安装了golang，还是把`cloudpan189-go`后缀改成*.sh?shell会用，go语言第一次用，感谢任何建议

**Comment by y377** [comment]
> 是啊，之前在Windows下运行的很完美，现在centos7请问怎么运行啊？也使用yum安装了golang，还是把`cloudpan189-go`后缀改成*.sh?shell会用，go语言第一次用，感谢任何解答！
> 目前的问题：
> 
> ```
> [root@transmission ~]# go run cloudpan189-go
> cannot find package "cloudpan189-go" in any of:
>         /usr/lib/golang/src/cloudpan189-go (from $GOROOT)
>         /root/go/src/cloudpan189-go (from $GOPATH)
> [root@transmission ~]#
> ```

好了，大家不要被*-go误导，跟shell一样用，
```
[root@transmission ~]# chmod +x cloudpan189-go
[root@transmission ~]# ./cloudpan189-go login
请输入用户名(手机号/邮箱/别名), 回车键提交 > 188****5678
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
天翼帐号登录成功:  188****5678@189.cn
```
