### ISSUE TITLE
Windows版本上传文件后文件名异常

### ISSUE THREAD

**Issue by LittleTurtle2333** [tickstep/cloudpan189-go#2]
Windows版本上传文件后，相对路径或者绝对路径都会导致上传后的文件的文件名为绝对路径。如上传1.mp4文件名会变成D:\1.mp4

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by LittleTurtle2333** [comment]
Linux上不会

**Comment by LittleTurtle2333** [comment]
绝对路径不会，相对路径会。之前说错了

**Comment by tickstep** [comment]
谢谢反馈，已修复，v0.0.4版本会合入。
