### ISSUE TITLE
0.0.9版本没有backup 功能

### ISSUE THREAD

**Issue by windyin** [tickstep/cloudpan189-go#25]
最新的release0.0.9版本没有backup 功能，是否可以编译一个新版，谢谢

**Comment by pongfcnkl** [comment]
下golang
go build

**Comment by windyin** [comment]
尝试运行  go get github.com/tickstep/cloudpan189-go/
出现如下提示
src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
 然后再bin目录下并没有找到可执行文件，我理解编译失败了？

**Comment by 52funny** [comment]
> 尝试运行 go get github.com/tickstep/cloudpan189-go/
> 出现如下提示
> src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> 然后再bin目录下并没有找到可执行文件，我理解编译失败了？

你应该git clone 项目然后 go build

**Comment by jinshuqishi2019** [comment]
> > 尝试运行 go get github.com/tickstep/cloudpan189-go/
> > 出现如下提示
> > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > 然后再bin目录下并没有找到可执行文件，我理解编译失败了？
> 
> 你应该git clone 项目然后 go build

能详细点吗？或者有编译好的分享下。

**Comment by pongfcnkl** [comment]
> 
> 
> > > 尝试运行 go get github.com/tickstep/cloudpan189-go/
> > > 出现如下提示
> > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > 然后再bin目录下并没有找到可执行文件，我理解编译失败了？
> > 
> > 
> > 你应该git clone 项目然后 go build
> 
> 能详细点吗？或者有编译好的分享下。

什么系统？

**Comment by jinshuqishi2019** [comment]
> > > > 尝试运行 go get github.com/tickstep/cloudpan189-go/
> > > > 出现如下提示
> > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > 然后再bin目录下并没有找到可执行文件，我理解编译失败了？
> > > 
> > > 
> > > 你应该git clone 项目然后 go build
> > 
> > 
> > 能详细点吗？或者有编译好的分享下。
> 
> 什么系统？

我的是linux-amd64,谢谢，我自己编译，出现很多问题，都不知道怎么解决。

**Comment by pongfcnkl** [comment]
> 
> 
> > > > > 尝试运行 go get github.com/tickstep/cloudpan189-go/
> > > > > 出现如下提示
> > > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > > 然后再bin目录下并没有找到可执行文件，我理解编译失败了？
> > > > 
> > > > 
> > > > 你应该git clone 项目然后 go build
> > > 
> > > 
> > > 能详细点吗？或者有编译好的分享下。
> > 
> > 
> > 什么系统？
> 
> 我的是linux-amd64,谢谢，我自己编译，出现很多问题，都不知道怎么解决。

试试这个
https://ddd.cowtransfer.com/s/defe732f890d48

**Comment by jinshuqishi2019** [comment]
> > > > 尝试运行 go get github.com/tickstep/cloudpan189-go/
> > > > 出现如下提示
> > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > 然后再bin目录下并没有找到可执行文件，我理解编译失败了？
> > > 
> > > 
> > > 你应该git clone 项目然后 go build
> > 
> > 
> > 能详细点吗？或者有编译好的分享下。
> 
> 什么系统？

我的是linux-amd64

> > > > > > 尝试运行 go get github.com/tickstep/cloudpan189-go/
> > > > > > 出现如下提示
> > > > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:149:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > > > src/github.com/tickstep/cloudpan189-api/cloudpan/apiutil/utils.go:154:5: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
> > > > > > 然后再bin目录下并没有找到可执行文件，我理解编译失败了？
> > > > > 
> > > > > 
> > > > > 你应该git clone 项目然后 go build
> > > > 
> > > > 
> > > > 能详细点吗？或者有编译好的分享下。
> > > 
> > > 
> > > 什么系统？
> > 
> > 
> > 我的是linux-amd64,谢谢，我自己编译，出现很多问题，都不知道怎么解决。
> 
> 试试这个
> https://ddd.cowtransfer.com/s/defe732f890d48

使用backup 和 upload都出现下面问题
/share/4312494 同步数据库打开失败,跳过该目录的备份 Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

**Comment by pongfcnkl** [comment]
> go-sqlite3 requires cgo to work. This is a stub

https://cowtransfer.com/s/99b89f8ec8fc4b

**Comment by jinshuqishi2019** [comment]
> > go-sqlite3 requires cgo to work. This is a stub
> 
> https://cowtransfer.com/s/99b89f8ec8fc4b

你这个文件运行出现错误
./cloudpan189-go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./cloudpan189-go)

我自己编译成功了，发现是go版本低的原因，更新最新版本后，发现默认编译的是0.0.9版本，这个问题是怎么解决好？

**Comment by pongfcnkl** [comment]
> 
> 
> > > go-sqlite3 requires cgo to work. This is a stub
> > 
> > 
> > https://cowtransfer.com/s/99b89f8ec8fc4b
> 
> 你这个文件运行出现错误
> ./cloudpan189-go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./cloudpan189-go)
> 
> 我自己编译成功了，发现是go版本低的原因，更新最新版本后，发现默认编译的是0.0.9版本，这个问题是怎么解决好？

感觉你的系统有问题，不会是那种很老的系统吧

**Comment by pongfcnkl** [comment]
> 
> 
> > > go-sqlite3 requires cgo to work. This is a stub
> > 
> > 
> > https://cowtransfer.com/s/99b89f8ec8fc4b
> 
> 你这个文件运行出现错误
> ./cloudpan189-go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./cloudpan189-go)
> 
> 我自己编译成功了，发现是go版本低的原因，更新最新版本后，发现默认编译的是0.0.9版本，这个问题是怎么解决好？

代码里的版本号本来就是0.0.9

**Comment by jinshuqishi2019** [comment]
> > > > go-sqlite3 requires cgo to work. This is a stub
> > > 
> > > 
> > > https://cowtransfer.com/s/99b89f8ec8fc4b
> > 
> > 
> > 你这个文件运行出现错误
> > ./cloudpan189-go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./cloudpan189-go)
> > 我自己编译成功了，发现是go版本低的原因，更新最新版本后，发现默认编译的是0.0.9版本，这个问题是怎么解决好？
> 
> 代码里的版本号本来就是0.0.9

谢谢你的帮忙，已经编译最新的版本啦，v0.1.0-dev

**Comment by tickstep** [comment]
0.1.0已经包含备份功能
