### ISSUE TITLE
amd64这个版本没有backup命令，什么时候可以更新下。

### ISSUE THREAD

**Issue by jinshuqishi2019** [tickstep/cloudpan189-go#32]
你好，同步这个功能挺好的，但是现在Releases的版本还没有，请问下什么时候有更新，谢谢。

**Comment by pongfcnkl** [comment]
下载golang和git
搞一下环境变量
下源码之后go build就出来了

**Comment by jinshuqishi2019** [comment]
> 下载golang和git
> 搞一下环境变量
> 下源码之后go build就出来了

我改变了GOPATH，提示缺少文件，于是将缺少的go get -u 下载，途中缺少/math/bits/bits，再编译出现许多错误，都不知怎么解决了。
![1](https://user-images.githubusercontent.com/57516638/109981652-12b08480-7d3c-11eb-9b12-cc3960686c2d.png)

**Comment by pongfcnkl** [comment]
> 
> 
> > 下载golang和git
> > 搞一下环境变量
> > 下源码之后go build就出来了
> 
> 我改变了GOPATH，提示缺少文件，于是将缺少的go get -u 下载，途中缺少/math/bits/bits，再编译出现许多错误，都不知怎么解决了。
> ![1](https://user-images.githubusercontent.com/57516638/109981652-12b08480-7d3c-11eb-9b12-cc3960686c2d.png)

如果不需要交叉编译就不用改变量，直接go build就行，直接生成符合你系统的软件

**Comment by jinshuqishi2019** [comment]
> > > 下载golang和git
> > > 搞一下环境变量
> > > 下源码之后go build就出来了
> > 
> > 
> > 我改变了GOPATH，提示缺少文件，于是将缺少的go get -u 下载，途中缺少/math/bits/bits，再编译出现许多错误，都不知怎么解决了。
> > ![1](https://user-images.githubusercontent.com/57516638/109981652-12b08480-7d3c-11eb-9b12-cc3960686c2d.png)
> 
> 如果不需要交叉编译就不用改变量，直接go build就行，直接生成符合你系统的软件
但是直接使用go build编译会出现很多找不到包的错误。例如下面的。
main.go:29:2: cannot find package "github.com/peterh/liner" in any of:
	/usr/lib/go-1.7/src/github.com/peterh/liner (from $GOROOT)
	/root/go/src/github.com/peterh/liner (from $GOPATH)

**Comment by jinshuqishi2019** [comment]
> > > 下载golang和git
> > > 搞一下环境变量
> > > 下源码之后go build就出来了
> > 
> > 
> > 我改变了GOPATH，提示缺少文件，于是将缺少的go get -u 下载，途中缺少/math/bits/bits，再编译出现许多错误，都不知怎么解决了。
> > ![1](https://user-images.githubusercontent.com/57516638/109981652-12b08480-7d3c-11eb-9b12-cc3960686c2d.png)
> 
> 如果不需要交叉编译就不用改变量，直接go build就行，直接生成符合你系统的软件

但是直接使用go build编译会出现很多找不到包的错误。例如下面的。
main.go:29:2: cannot find package "github.com/peterh/liner" in any of:
/usr/lib/go-1.7/src/github.com/peterh/liner (from $GOROOT)
/root/go/src/github.com/peterh/liner (from $GOPATH)

**Comment by pongfcnkl** [comment]
> 
> 
> > > > 下载golang和git
> > > > 搞一下环境变量
> > > > 下源码之后go build就出来了
> > > 
> > > 
> > > 我改变了GOPATH，提示缺少文件，于是将缺少的go get -u 下载，途中缺少/math/bits/bits，再编译出现许多错误，都不知怎么解决了。
> > > ![1](https://user-images.githubusercontent.com/57516638/109981652-12b08480-7d3c-11eb-9b12-cc3960686c2d.png)
> > 
> > 
> > 如果不需要交叉编译就不用改变量，直接go build就行，直接生成符合你系统的软件
> 
> 但是直接使用go build编译会出现很多找不到包的错误。例如下面的。
> main.go:29:2: cannot find package "github.com/peterh/liner" in any of:
> /usr/lib/go-1.7/src/github.com/peterh/liner (from $GOROOT)
> /root/go/src/github.com/peterh/liner (from $GOPATH)

你这是本地机吗？没挂代理？

**Comment by jinshuqishi2019** [comment]
> > > > > 下载golang和git
> > > > > 搞一下环境变量
> > > > > 下源码之后go build就出来了
> > > > 
> > > > 
> > > > 我改变了GOPATH，提示缺少文件，于是将缺少的go get -u 下载，途中缺少/math/bits/bits，再编译出现许多错误，都不知怎么解决了。
> > > > ![1](https://user-images.githubusercontent.com/57516638/109981652-12b08480-7d3c-11eb-9b12-cc3960686c2d.png)
> > > 
> > > 
> > > 如果不需要交叉编译就不用改变量，直接go build就行，直接生成符合你系统的软件
> > 
> > 
> > 但是直接使用go build编译会出现很多找不到包的错误。例如下面的。
> > main.go:29:2: cannot find package "github.com/peterh/liner" in any of:
> > /usr/lib/go-1.7/src/github.com/peterh/liner (from $GOROOT)
> > /root/go/src/github.com/peterh/liner (from $GOPATH)
> 
> 你这是本地机吗？没挂代理？

有代理，分国内国外分流，我还修改了export GOPROXY=https://goproxy.io,direct，而且使用go get -u github.com/peterh/liner
是可以下载文件的。
