### ISSUE TITLE
使用backup的时候可以排除指定的目录吗

### ISSUE THREAD

**Issue by conscloud** [tickstep/cloudpan189-go#35]
对群晖的目录进行备份，能否排除掉群晖生成的@eaDir目录。
不然会经常因为在遍历@eaDir目录是会出现遍历错误。

![image](https://user-images.githubusercontent.com/18484709/110061484-a2891980-7da2-11eb-8d13-020dd95c3fc5.png)

**Comment by imblowsnow** [comment]
i also want

**Comment by conscloud** [comment]
upload可以排除指定文件或者目录，但backup还不支持。

**Comment by tickstep** [comment]
新版本已经支持
