### ISSUE TITLE
登录显示验证码解析错误

### ISSUE THREAD

**Issue by Qa7060123** [tickstep/cloudpan189-go#4]
错误:
验证码解析错误: unexpected EOF

但是网页密码登录成功
可以cookie登录吗，可以的话文件在哪

**Comment by tickstep** [comment]
> 错误:
> 
> 验证码解析错误: unexpected EOF
> 
> 
> 
> 
> 
> 但是网页密码登录成功
> 
> 可以cookie登录吗，可以的话文件在哪
> 
> 
> 
> 

这个有验证ok么？

**Comment by y377** [comment]
提示验证失败，更换ip就可解决；
如果频繁登录的/切换账号的，建议使用归属地pppoe家庭宽带登录，不建议使用固定ip（比如云服务器）
