### ISSUE TITLE
文件未曾上传，无法秒传

### ISSUE THREAD

**Issue by xiaokaixuan** [tickstep/cloudpan189-go#45]
**有的文件（大小超过1G）官方客户端可以秒传，本工具不行，提示`文件未曾上传，无法秒传`**
> 比如这个文件 `{"md5":"85C114F7CDF1C86323A01457AFC0F205","size":1232111652,"path":"/AMOVIES/080113_636.mp4","lastOpTime":"2021-06-28 19:14:36"}`
> 这个是我用官方客户端秒传后导出的Meta

**Comment by xiaokaixuan** [comment]
昨天抓包看了下接口，官方客户端上传接口已经改了。

**Comment by xiaoyaofenfen** [comment]
确实，换了接口，还是参数加密的，天翼云盘近段时间换接口贼勤快(ಥ_ಥ)
