### ISSUE TITLE
希望增加定时备份功能

### ISSUE THREAD

**Issue by hybiz** [tickstep/cloudpan189-go#47]
这个程序不错，很方便的。希望增加设定好时间参数后，定时执行backup命令。

**Comment by xiaoyaofenfen** [comment]
这个需求建议使用操作系统自身的定时任务触发器实现，例如linux的corntab定时任务执行器，例如

# 例如，每天凌晨2点执行备份
0 2 * * * cloudpan189-go backup /home/users/backup_folder /pan_backup_folder

**Comment by hybiz** [comment]
已经搞定了，谢谢。
