### ISSUE TITLE
树莓派登录错误

### ISSUE THREAD

**Issue by Qa7060123** [tickstep/cloudpan189-go#5]
非sudo
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2f5ab0]

goroutine 1 [running]:
github.com/tickstep/cloudpan189-go/cloudpan/apierror.(*ApiError).Error(...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/cloudpan/apierror/api_error.go:58
github.com/tickstep/cloudpan189-go/cloudpan.LoginWithCaptcha(0x1680160, 0xb, 0x141a1e0, 0xe, 0x0, 0x0, 0x16ff350, 0x50)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/cloudpan/login.go:87 +0x3dc
github.com/tickstep/cloudpan189-go/cloudpan.Login(0x1680160, 0xb, 0x141a1e0, 0xe, 0xe, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/cloudpan/login.go:67 +0x11c
github.com/tickstep/cloudpan189-go/internal/command.RunLogin(0x1680160, 0xb, 0x141a1e0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/internal/command/login.go:32 +0xc0
main.main.func2(0x16940b0, 0x83d2b8, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/main.go:329 +0xf0
github.com/urfave/cli.HandleAction(0x41b518, 0x4b3d08, 0x16940b0, 0x16940b0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
github.com/urfave/cli.Command.Run(0x48ccaa, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4993c5, 0x18, 0x0, ...)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
github.com/urfave/cli.(*App).Run(0x15feee0, 0x1688000, 0x2, 0x2, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
main.main.func1(0x15104d0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/main.go:298 +0x508
github.com/urfave/cli.HandleAction(0x413108, 0x164f330, 0x15104d0, 0x15104d0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x6c
github.com/urfave/cli.(*App).Run(0x15feee0, 0x149c020, 0x1, 0x1, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x454
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/main.go:1407 +0x2740

sudo 运行

请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
APP登录失败： json: cannot unmarshal number 1600422955375 into Go struct field accessTokenResp.expiresIn of type int
登录失败

**Comment by tickstep** [comment]
> 非sudo
> 
> 请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> 
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2f5ab0]
> 
> 
> 
> goroutine 1 [running]:
> 
> github.com/tickstep/cloudpan189-go/cloudpan/apierror.(*ApiError).Error(...)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/cloudpan/apierror/api_error.go:58
> 
> github.com/tickstep/cloudpan189-go/cloudpan.LoginWithCaptcha(0x1680160, 0xb, 0x141a1e0, 0xe, 0x0, 0x0, 0x16ff350, 0x50)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/cloudpan/login.go:87 +0x3dc
> 
> github.com/tickstep/cloudpan189-go/cloudpan.Login(0x1680160, 0xb, 0x141a1e0, 0xe, 0xe, 0x0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/cloudpan/login.go:67 +0x11c
> 
> github.com/tickstep/cloudpan189-go/internal/command.RunLogin(0x1680160, 0xb, 0x141a1e0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/internal/command/login.go:32 +0xc0
> 
> main.main.func2(0x16940b0, 0x83d2b8, 0x0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/main.go:329 +0xf0
> 
> github.com/urfave/cli.HandleAction(0x41b518, 0x4b3d08, 0x16940b0, 0x16940b0, 0x0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
> 
> github.com/urfave/cli.Command.Run(0x48ccaa, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4993c5, 0x18, 0x0, ...)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
> 
> github.com/urfave/cli.(*App).Run(0x15feee0, 0x1688000, 0x2, 0x2, 0x0, 0x0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
> 
> main.main.func1(0x15104d0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/main.go:298 +0x508
> 
> github.com/urfave/cli.HandleAction(0x413108, 0x164f330, 0x15104d0, 0x15104d0, 0x0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x6c
> 
> github.com/urfave/cli.(*App).Run(0x15feee0, 0x149c020, 0x1, 0x1, 0x0, 0x0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x454
> 
> main.main()
> 
>         /Users/tickstep/Documents/Workspace/go/projects/cloudpan189-go/src/github.com/tickstep/cloudpan189-go/main.go:1407 +0x2740
> 
> 
> 
> 
> 
> 
> 
> 
> 
> sudo 运行
> 
> 
> 
> 
> 
> 请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
> 
> APP登录失败： json: cannot unmarshal number 1600422955375 into Go struct field accessTokenResp.expiresIn of type int
> 
> 登录失败
> 
> 
> 
> 

这个有验证修复了么？没有问题的话我就先关闭了
