### ISSUE TITLE
通过本程序上传文件，是否失去官方客户端秒传功能

### ISSUE THREAD

**Issue by wdjoys** [tickstep/cloudpan189-go#6]
非常感谢开源提供
官方客户端上传常用文件会秒传，我用本程序传了几个常用的.iso系统包没有秒传，是否失去官方客户端秒传功能。

**Comment by tickstep** [comment]
是的，秒传是没做，有时间再补上(⁎⁍̴̛ᴗ⁍̴̛⁎)

**Comment by tickstep** [comment]
已增加上传秒传功能，会在v0.0.7版本合入

**Comment by wdjoys** [comment]
感谢大佬，赞赞赞
