### ISSUE TITLE
请求多线程！！！

### ISSUE THREAD

**Issue by nomoneynolife** [tickstep/cloudpan189-go#61]
示例()
cloudpan189-go config set -max_backup_parallel 15 // 15 的下载并发

上传
cloudpan189-go config set --max_upload_parallel 15 / 15 的上传并发

OPTIONS:
--cache_size value 下载缓存
--max_download_parallel value 下载网络连接的最大并发量 (default: 0)
--max_upload_parallel value 上传网络连接的最大并发量 (default: 0)
--max_download_load value 同时进行下载文件的最大数量 (default: 0)
--max_download_rate value 限制最大下载速度, 0代表不限制
--max_upload_rate value 限制最大上传速度, 0代表不限制
--savedir value 下载文件的储存目录
--proxy value 设置代理, 支持 http/socks5 代理
--local_addrs value 设置本地网卡地址, 多个地址用逗号隔开

**Comment by nomoneynolife** [comment]
抱歉，在 -h 的确没看到，
不经意间，输入
cloudpan189-go config set -max_backup_parallel 15
报错，
弹出了正确的配置文档。~

NAME:
   cloudpan189-go config set - 修改程序配置项

USAGE:
   cloudpan189-go config set [arguments...]

DESCRIPTION:

  注意:
    可通过设置环境变量 CLOUD189_CONFIG_DIR, 指定配置文件存放的目录.

    cache_size 的值支持可选设置单位, 单位不区分大小写, b 和 B 均表示字节的意思, 如 64KB, 1MB, 32kb, 65536b, 65536
    max_download_rate, max_upload_rate 的值支持可选设置单位, 单位为每秒的传输速率, 后缀'/s' 可省略, 如 2MB/s, 2MB, 2m, 2mb 均为一个意思

  例子:
    cloudpan189-go config set -cache_size 64KB
    cloudpan189-go config set -cache_size 16384 -max_download_parallel 200 -savedir D:/download

OPTIONS:
   --cache_size value             下载缓存
   --max_download_parallel value  下载网络连接的最大并发量 (default: 0)
   --max_upload_parallel value    上传网络连接的最大并发量 (default: 0)
   --max_download_load value      同时进行下载文件的最大数量 (default: 0)
   --max_download_rate value      限制最大下载速度, 0代表不限制
   --max_upload_rate value        限制最大上传速度, 0代表不限制
   --savedir value                下载文件的储存目录
   --proxy value                  设置代理, 支持 http/socks5 代理
   --local_addrs value            设置本地网卡地址, 多个地址用逗号隔开

**Comment by tickstep** [comment]
谢谢反馈，最新版本已支持。上传和下载都是可以多人并发执行
