### ISSUE TITLE
没有检测机制，已经存在的文件会再次上传

### ISSUE THREAD

**Issue by fabaoin** [tickstep/cloudpan189-go#71]
已经存在的文件会再次上传
如果是秒传，会再次在同一目录下生成一个形如2022.09.17-15.39(20220918160750)的文件

如果不检测秒传，会再次进行上传。应该是有检测已经存在的文件就跳过。

**Comment by fabaoin** [comment]
[3] 准备上传: 2022/09_17/2022.09.17-16.00.flv=>/2022/09_17/2022.09.17-16.00.flv
[3] 检测秒传中, 请稍候...
[3] 秒传成功, 保存到网盘路径:/2022/09_17/2022.09.17-16.00.flv

结果网盘里生成一个  2022.09.17-16.00(20220922183800).flv
而不是跳过这个文件。

**Comment by tickstep** [comment]
> 
> 
> [3] 准备上传: 2022/09_17/2022.09.17-16.00.flv=>/2022/09_17/2022.09.17-16.00.flv
> 
> [3] 检测秒传中, 请稍候...
> 
> [3] 秒传成功, 保存到网盘路径:/2022/09_17/2022.09.17-16.00.flv
> 
> 
> 
> 结果网盘里生成一个  2022.09.17-16.00(20220922183800).flv
> 
> 而不是跳过这个文件。
> 
> 

upload命令增加ow选项
