### ISSUE TITLE
提示APP登录失败

### ISSUE THREAD

**Issue by fate-think** [tickstep/cloudpan189-go#80]
登录时间是2023年05月04日，测试的是最新版cloudpan189-go

**Comment by SuNine520** [comment]
同问，求解决

**Comment by wangozoo** [comment]
同问

**Comment by icerwong** [comment]
我两个号，一个177的5g会员，登录不了
另一个139的非会员，可以

**Comment by icerwong** [comment]
我发现为啥不能登录了。我把139的号充一会员，就登录不了了。。。。。

**Comment by fate-think** [comment]
> 我发现为啥不能登录了。我把139的号充一会员，就登录不了了。。。。。

感谢，原来问题出在这里，当时我登录失败的也是会员号，现在试试没会员的号

**Comment by fate-think** [comment]
## 已解决
- 登录非会员账号即可
