### ISSUE TITLE
要是能加入家庭云的操作就妙了...

### ISSUE THREAD

**Issue by xiaokaixuan** [tickstep/cloudpan189-go#9]

**Comment by xiaokaixuan** [comment]
貌似只要MD5和Size就能秒传，我有个大胆的想法……类似[115转存助手](https://greasyfork.org/zh-CN/scripts/386724-115%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8B)

**Comment by tickstep** [comment]
家庭云的功能放后面点了，主要是个人云盘用得多(⁎⁍̴̛ᴗ⁍̴̛⁎)

**Comment by tickstep** [comment]
> 貌似只要MD5和Size就能秒传，我有个大胆的想法……类似[115转存助手](https://greasyfork.org/zh-CN/scripts/386724-115%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8B)

这个确实可以搞，只要知道文件md5和大小就可以转存文件到自己网盘了。⁄(⁄ ⁄ ⁄ω⁄ ⁄ ⁄)⁄
不过天翼云盘没有存md5值，md5只能通过自己本地文件算出来

**Comment by xiaokaixuan** [comment]
百度网盘和微云里的文件 可以看到MD5

**Comment by tickstep** [comment]
v0.0.8已经集成家庭云功能
